language: node_js
node_js:
  - "8.12.0"
services:
  - postgresql
addons:
  postgresql: "9.6"
before_install:
  - npm install sequelize-cli yarn -g
before_script:
  - psql -c 'create database test_pg_db;' -U postgres
  - psql -c "CREATE USER real_pg_user;" -U postgres
  - NODE_ENV=test
  - openssl genpkey -algorithm RSA -out ./config/private_key.pem -pkeyopt rsa_keygen_bits:512
  - openssl rsa -pubout -in ./config/private_key.pem -out ./config/public_key.pem
script:
- yarn run test
after_script:
- yarn run report-coverage