language: node_js
node_js:
  - "8.12.0"
services:
  - postgresql
addons:
  postgresql: "9.6"
before_install:
  - npm install sequelize-cli yarn -g
before_script:
  - psql -c 'create database test_assessment;' -U postgres
  - psql -c "CREATE USER boswellgathu;" -U postgres
  - NODE_ENV=test
script:
- yarn run test
after_script:
- yarn run report-coverage